name: Python App CI/CD with Docker and Testing

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pip install pytest pytest-cov
          pytest TestRecommender.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

  build-and-deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags:
            - johansono/vacation-planner:v1.0.0:${{ github.sha }}

      - name: Deploy the Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOCKER_REPO  }}
          username: ${{ secrets.DOCKER_USER  }}
          password: ${{ secrets.DOCKER_PASS }}
          script: |
            docker pull my-docker-registry/my-app:${{ github.sha }}
            docker run -d --name johansono/vacation-planner:v1.0.0 -p 80:80 johansono/vacation-planner:v1.0.0:${{ github.sha }}
