name: Python App CI/CD with Docker and Testing

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
      - name: Run tests
        run: |
          pip install googlemaps scikit-learn pandas coverage
          python3 -m coverage run TestRecommender.py 
          
      - name: Coverage report
        run: |
          python3 coverage report -m

  build-and-deploy:
    runs-on: ubuntu-latest
    
    needs: test

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: johansono/vacation-planner:v1.0.1
