name: Python App CI/CD with Docker and Testing

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: johansono/vacation-planner:v1.0.1
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy the Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOCKER_REPO  }}
          username: ${{ secrets.DOCKER_USERNAME  }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          script: |
            docker pull my-docker-registry/my-app:${{ github.sha }}
            docker run -d --name johansono/vacation-planner:v1.0.1 -p 80:80 johansono/vacation-planner:v1.0.1:${{ github.sha }}
